export const viewColumnDefs = [
  {
    field: 'customer_name',
    headerName: 'Customer',
    filter: true,
    flex: 1.3,
    sortable: false,
  },
  {
    field: 'procurement_specialist',
    headerName: 'P.S.',
    sortable: false,
    flex: 0.6,
    cellStyle: { textAlign: 'center' },
  },
  {
    field: 'sales_order',
    headerName: 'SO#',
    filter: true,
    flex: 1.16,
    sortable: false,
  },
  {
    field: 'received_date',
    headerName: 'Date',
    filter: true,
    flex: 1.14,
    sortable: false,
  },
  {
    field: 'part_number',
    headerName: 'Part#',
    filter: true,
    flex: 1.02,
    sortable: false,
  },
  {
    field: 'part_description',
    headerName: 'Part Descr.',
    filter: true,
    sortable: false,
    flex: 2,
  },
  {
    field: 'serial_number',
    headerName: 'Serial#',
    filter: true,
    flex: 1,
    sortable: false,
  },
  {
    field: 'quantity',
    headerName: 'Qty',
    sortable: false,
    flex: 0.61,
    cellStyle: { textAlign: 'center' },
  },
  {
    valueGetter: (params) =>
      `${params.data.box_number} / ${params.data.box_number_total}`,
    headerName: 'Box',
    sortable: false,
    flex: 0.64,
    cellStyle: { textAlign: 'center' },
  },
  {
    field: 'location',
    headerName: 'Location',
    filter: false,
    flex: 1.28,
    sortable: false,
  },
  {
    field: 'notes',
    headerName: 'Notes',
    filter: false,
    flex: 1,
    sortable: false,
  },
];
